// 'use client';
export const dynamic = 'force-dynamic';
export const revalidate = 0;
import { getUserSessionServer } from "@/auth/actions/auth.actions";
import prisma from "@/lib/prisma";
import { NewTodo } from "@/todos/components/NewTodo";
import { TodosGrid } from "@/todos/components/TodosGrid";
import { type Metadata } from "next";
import { redirect } from "next/navigation";
// import { useEffect } from "react";

export const metadata: Metadata = {
  title: 'Server Todos',
  description: 'Generated by create next app',
}

export default async function ServerTodosPage() {
  const user = await getUserSessionServer();
  if(!user) redirect('/api/auth/signin');

  const todos = await prisma.todo.findMany({
    where:{
      userId:user.id
    },
    orderBy: [
      {
        description: 'asc'
      }
    ]
  });
  // useEffect(() => {
  //   fetch('/api/todos')
  //     .then(res => res.json())
  //     .then(data => console.log(data))
  // }, []);

  return (
    <>
      <span className="text-3xl mb-10">Server Actions</span>
      <div className="w-full px-3 m-5">
        <NewTodo />
      </div>
      <TodosGrid todos={todos} />
    </>
  );
}