import { WidgetItem } from "@/components";
import { type Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default async function DashboardPage() {
  const session = await getServerSession(authOptions);
  if(!session) {
    redirect('/api/auth/signin');
  }
  return (
    <div className="grid gap-6 grid-cols-1">
      <WidgetItem title="Usuario conectad - server side">
        <div className="flex flex-col">
          {
            JSON.stringify(session.user)
          }
        </div>
      </WidgetItem>
    </div>
  );
}